apiVersion: v1
kind: Secret
metadata:
  name: ptyxiakh-secret
type: Opaque
stringData:
  OPENAI_API_KEY: "sk-REPLACE_ME"
  PG_USER: raguser
  PG_PASSWORD: ragpass
  PG_DB: ragdb
  CORS_ORIGIN: "http://34.53.161.193:30000"
