"""
gradio_app.py — Gradio chat UI for the Travel Assistant.

Connects to the FastAPI backend via the streaming endpoint and renders
tokens progressively so the UI looks like a live typing ChatGPT experience.

Run locally:
    python ui/gradio_app.py
Or inside Docker: the Dockerfile.gradio sets this as the entry point.
"""

import os
import httpx
import gradio as gr

# Backend URL — override via environment variable (set in docker-compose / K8s)
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")
STREAM_URL  = f"{BACKEND_URL}/chat/stream"
HEALTH_URL  = f"{BACKEND_URL}/health"


def check_backend() -> str:
    """Return a status string shown in the UI header."""
    try:
        r = httpx.get(HEALTH_URL, timeout=3.0)
        if r.status_code == 200:
            return "🟢 Backend connected"
    except Exception:
        pass
    return "🔴 Backend unreachable — start the FastAPI server first"


def _format_history(history: list) -> list[dict]:
    """
    Convert Gradio history format → backend format.

    Gradio ChatInterface passes history as a list of [user_msg, assistant_msg] pairs.
    The backend expects: [{"user": "...", "assistant": "..."}, ...]
    """
    formatted = []
    for turn in history:
        if isinstance(turn, (list, tuple)) and len(turn) == 2:
            formatted.append({"user": turn[0] or "", "assistant": turn[1] or ""})
    return formatted


def stream_chat(message: str, history: list) -> str:
    """
    Generator function called by Gradio ChatInterface.
    Streams tokens from POST /chat/stream and yields progressively
    accumulated text, which Gradio renders in real time.

    Passes conversation history to the backend so retrieval and generation
    are context-aware (history-aware RAG).
    """
    partial = ""
    try:
        with httpx.stream(
            "POST",
            STREAM_URL,
            json={
                "message": message,
                "history": _format_history(history),
            },
            timeout=300.0,   # Mistral on CPU can take up to 5 min
        ) as response:
            response.raise_for_status()
            for chunk in response.iter_text():
                partial += chunk
                yield partial
    except httpx.ConnectError:
        yield (
            "❌ Cannot connect to the backend. "
            f"Make sure the FastAPI server is running at {BACKEND_URL}."
        )
    except Exception as exc:
        yield f"❌ Error: {exc}"


# ── Example queries shown below the input box ────────────────────────────────
EXAMPLES = [
    ["Θέλω να πάω Ρώμη 5 μέρες με 700€. Φτιάξε μου πρόγραμμα."],
    ["Ταξίδι Τόκιο 7 μέρες με budget 1500€. Τι προτείνεις;"],
    ["Παρίσι 3 μέρες με 500€. Ποια αξιοθέατα να δω και πόσο κοστίζουν;"],
    ["Barcelona 4 days with €600 budget. Give me a detailed itinerary."],
    ["Θέλω Σαντορίνη + Αθήνα 6 μέρες με 900€. Πώς να οργανωθώ;"],
    ["Japan 10 days budget 2000€. Best cities and itinerary please."],
]

# ── Build Gradio UI ──────────────────────────────────────────────────────────
with gr.Blocks(
    title="🌍 Travel Assistant",
    theme=gr.themes.Soft(primary_hue="blue", secondary_hue="sky"),
    css="""
        .header-box { text-align: center; padding: 16px 0 8px; }
        .status-box { text-align: center; font-size: 0.85em; color: #555; margin-bottom: 8px; }
        footer { display: none !important; }
    """,
) as demo:
    gr.HTML(
        """
        <div class="header-box">
            <h1>🌍 Travel Assistant</h1>
            <p style="color:#555; margin:0;">
                Powered by <b>Mistral 7B</b> + <b>RAG</b> (Italy, France, Spain, Greece, Japan)
            </p>
        </div>
        """
    )

    status = gr.Markdown(check_backend(), elem_classes="status-box")

    # In Gradio 4.x, don't pre-render gr.Chatbot() when inside gr.Blocks —
    # pass constructor kwargs via additional_inputs instead; let ChatInterface
    # create its own chatbot to avoid the DuplicateBlockError.
    chat_ui = gr.ChatInterface(
        fn=stream_chat,
        examples=EXAMPLES,
        title="",          # title handled by the HTML block above
        submit_btn="Send",
        retry_btn="Retry",
        undo_btn="Undo",
        clear_btn="Clear",
    )

    gr.Markdown(
        """
        ---
        **Supported destinations:** Italy 🇮🇹 · France 🇫🇷 · Spain 🇪🇸 · Greece 🇬🇷 · Japan 🇯🇵
        *Responses are generated by a local Mistral 7B model — no data is sent to the cloud.*
        """,
        elem_classes="status-box",
    )


if __name__ == "__main__":
    demo.launch(
        server_name="0.0.0.0",
        server_port=int(os.getenv("GRADIO_PORT", "7860")),
        share=False,
    )
